import { Injectable, signal, effect } from '@angular/core';

export type Language = 'en' | 'es';

@Injectable({
    providedIn: 'root'
})
export class SettingsService {
    darkMode = signal<boolean>(localStorage.getItem('darkMode') === 'true');
    language = signal<Language>((localStorage.getItem('language') as Language) || 'en');

    // Basic translations dictionary
    private translations: any = {
        en: {
            dashboard: 'Dashboard',
            patients: 'Patients',
            alerts: 'Alerts',
            settings: 'Settings',
            system_settings: 'System Settings',
            profile_settings: 'Professional Profile',
            security: 'Security',
            preferences: 'Preferences',
            dark_mode: 'Dark Mode',
            system_language: 'System Language',
            save_changes: 'Save Changes',
            change_password: 'Change Password',
            current_password: 'Current Password',
            new_password: 'New Password',
            confirm_password: 'Confirm Password',
            logout: 'Logout',
            portal_title: 'S-park Portal',
            welcome: 'Welcome',
            total_patients: 'Total Patients',
            high_risk: 'High Risk',
            tests_performed: 'Tests Performed',
            last_test: 'Last Test',
            recent_activity: 'Recent Activity',
            clinical_alerts: 'Clinical Alerts',
            patient_directory: 'Patient Directory',
            register_patient: 'Register Patient',
            search_placeholder: 'Search by name or ID...',
            filter: 'Filter',
            export: 'Export',
            risk_level: 'Risk Level',
            actions: 'Actions',
            view_detail: 'View Detail',
            new_test: 'New Test',
            edit: 'Edit',
            invalid_login: 'Invalid email or password.',
            email_required: 'Email is required.',
            password_required: 'Password is required.',
            field_required: 'This field is required.',
            register_new_patient: 'Register New Patient',
            first_name: 'First Name',
            last_name: 'Last Name',
            age: 'Age',
            gender: 'Gender',
            male: 'Male',
            female: 'Female',
            other: 'Other',
            phone: 'Phone',
            email: 'Email',
            initial_diagnosis: 'Initial Diagnosis',
            cancel: 'Cancel',
            save_patient: 'Save Patient',
            edit_patient: 'Edit Patient',
            delete: 'Delete',
            required_fields_msg: 'Please complete all required fields.',
            // New Dashboard translations
            this_month: 'this month',
            at_risk_note: 'Requires attention',
            historical_total: 'Historical total',
            two_hours_ago: '2h ago',
            patient: 'Patient',
            date: 'Date',
            test_id: 'Test ID',
            status: 'Status',
            low_risk: 'Low Risk',
            medium_risk: 'Medium Risk',
            view_patient: 'View Patient',
            // New Alerts translations
            clinical_alerts_title: 'Clinical Alerts',
            total_today: 'Total today',
            critical: 'Critical',
            alert_level: 'Alert Level',
            period: 'Period',
            last_24h: 'Last 24 hours',
            last_7d: 'Last 7 days',
            current_month: 'Current month',
            clinical_reason: 'Clinical Reason',
            view_file: 'View File',
            all: 'All',
            // Profile translations
            professional_profile: 'Professional Profile',
            profile_desc: 'Manage your personal information and medical credentials',
            profile_info: 'Profile Information',
            change_photo: 'Change photo',
            full_name: 'Full Name',
            license_number: 'Medical License Number',
            hospital_clinic: 'Hospital or Clinic',
            specialty_label: 'Specialty',
            phone_number: 'Phone Number',
            profile_updated: 'Profile information updated successfully.',
            passwords_dont_match: 'New passwords do not match.',
            password_updated: 'Password updated successfully.',
            // Breadcrumbs
            bc_dashboard: 'Dashboard',
            bc_patients: 'Patients',
            bc_patient_detail: 'Patient Detail',
            bc_alerts: 'Alerts',
            bc_profile: 'Profile',
            bc_test_detail: 'Test Detail',
            // Risk levels (standalone)
            high: 'High',
            medium: 'Medium',
            low: 'Low',
            pending: 'Pending',
            // Patient Detail
            print_report: 'Print Report',
            age_label: 'Age',
            gender_label: 'Gender',
            diagnosis_label: 'Diagnosis',
            current_status: 'Current Status',
            clinical_observations: 'Clinical Observations',
            edit_notes: 'Edit notes',
            write_obs_placeholder: 'Write observations here...',
            biomarker_evolution: 'Biomarker Evolution',
            clinical_analysis: 'Clinical Analysis',
            voice_test_history: 'Voice Test History',
            result: 'Result',
            view: 'View',
            stable: 'Stable',
            // Time/Period
            years_old: 'years old',
            // Pagination
            previous: 'Previous',
            next: 'Next',
            of: 'of',
            // Doctors and Assignments
            doctors_management: 'Doctor Management',
            doctor_patients_relation: 'Patient Assignments',
            new_doctor: '+ New Doctor',
            specialty: 'Specialty',
            all_specialties: 'All Specialties',
            view_patients: 'View Patients',
            assigned_patients: 'Assigned Patients',
            doctor_directory_desc: 'Central directory of health professionals',
            doctor_assignments_desc: 'List of patients by medical professional',
            full_name_col: 'Full Name',
            license_col: 'License No.',
            status_col: 'Status',
            active_status: 'Active',
            inactive_status: 'Inactive',
            search_doctor_placeholder: 'Search by name...',
            back_to_doctors: 'Back to doctors list',
            total_patients_assigned: 'total patients assigned',
            // Clinical Notes
            clinical_notes: 'Clinical Notes',
            add_note: 'Add Note',
            note_type: 'Type',
            seguimiento: 'Follow-up',
            observacion: 'Observation',
            inicial: 'Initial Diagnosis',
            save_note: 'Save Note',
            no_diagnosis_yet: 'No initial diagnosis registered yet.',
            invalid_email_format: 'Enter a valid email address.',
            password_too_short: 'Password must be at least 6 characters long.',
            html_not_allowed: 'HTML tags are not allowed for security reasons.',
            invalid_phone_format: 'Enter a valid 10-digit phone number.',
            no_numbers_allowed: 'Numbers are not allowed in this field.',
            only_numbers_allowed: 'Only numbers are allowed in this field.'
        },
        es: {
            dashboard: 'Panel de Control',
            patients: 'Pacientes',
            alerts: 'Alertas',
            settings: 'Configuración',
            system_settings: 'Configuración del Sistema',
            profile_settings: 'Perfil Profesional',
            security: 'Seguridad',
            preferences: 'Preferencias',
            dark_mode: 'Modo Oscuro',
            system_language: 'Idioma del Sistema',
            save_changes: 'Guardar Cambios',
            change_password: 'Cambiar Contraseña',
            current_password: 'Contraseña Actual',
            new_password: 'Nueva Contraseña',
            confirm_password: 'Confirmar Contraseña',
            logout: 'Cerrar Sesión',
            portal_title: 'Portal S-park',
            welcome: 'Bienvenido',
            total_patients: 'Total Pacientes',
            high_risk: 'Riesgo Alto',
            tests_performed: 'Pruebas Realizadas',
            last_test: 'Última Prueba',
            recent_activity: 'Actividad Reciente',
            clinical_alerts: 'Alertas Clínicas',
            patient_directory: 'Directorio de Pacientes',
            register_patient: 'Registrar Paciente',
            search_placeholder: 'Buscar por nombre o ID...',
            filter: 'Filtrar',
            export: 'Exportar',
            risk_level: 'Nivel de Riesgo',
            actions: 'Acciones',
            view_detail: 'Ver Detalle',
            new_test: 'Nueva Prueba',
            edit: 'Editar',
            invalid_login: 'Correo o contraseña incorrectos.',
            email_required: 'El correo es obligatorio.',
            password_required: 'La contraseña es obligatoria.',
            field_required: 'Este campo es obligatorio.',
            register_new_patient: 'Registrar Nuevo Paciente',
            first_name: 'Nombre(s)',
            last_name: 'Apellidos',
            age: 'Edad',
            gender: 'Género',
            male: 'Masculino',
            female: 'Femenino',
            other: 'Otro',
            phone: 'Teléfono',
            email: 'Correo Electrónico',
            initial_diagnosis: 'Diagnóstico Inicial',
            cancel: 'Cancelar',
            save_patient: 'Guardar Paciente',
            edit_patient: 'Editar Paciente',
            delete: 'Eliminar',
            required_fields_msg: 'Por favor complete los campos obligatorios.',
            // New Dashboard translations
            this_month: 'este mes',
            at_risk_note: 'Requiere atención',
            historical_total: 'Total histórico',
            two_hours_ago: 'Hace 2h',
            patient: 'Paciente',
            date: 'Fecha',
            test_id: 'ID Prueba',
            status: 'Estado',
            low_risk: 'Bajo Riesgo',
            medium_risk: 'Riesgo Medio',
            view_patient: 'Ver Paciente',
            // New Alerts translations
            clinical_alerts_title: 'Alertas Clínicas',
            total_today: 'Total hoy',
            critical: 'Críticas',
            alert_level: 'Nivel de Alerta',
            period: 'Periodo',
            last_24h: 'Últimas 24 horas',
            last_7d: 'Últimos 7 días',
            current_month: 'Mes actual',
            clinical_reason: 'Motivo Clínico',
            view_file: 'Ver Expediente',
            all: 'Todos',
            // Profile translations
            professional_profile: 'Perfil Profesional',
            profile_desc: 'Gestiona tu información personal y credenciales médicas',
            profile_info: 'Información de Perfil',
            change_photo: 'Cambiar foto',
            full_name: 'Nombre Completo',
            license_number: 'Número de Licencia Médica',
            hospital_clinic: 'Hospital o Clínica',
            specialty_label: 'Especialidad',
            phone_number: 'Número de Teléfono',
            profile_updated: 'Información de perfil actualizada correctamente.',
            passwords_dont_match: 'Las contraseñas nuevas no coinciden.',
            password_updated: 'Contraseña actualizada con éxito.',
            // Breadcrumbs
            bc_dashboard: 'Dashboard',
            bc_patients: 'Pacientes',
            bc_patient_detail: 'Detalle de Paciente',
            bc_alerts: 'Alertas',
            bc_profile: 'Perfil',
            bc_test_detail: 'Detalle de Prueba',
            // Risk levels (standalone)
            high: 'Alta',
            medium: 'Medio',
            low: 'Bajo',
            pending: 'Pendiente',
            // Patient Detail
            print_report: 'Imprimir Reporte',
            age_label: 'Edad',
            gender_label: 'Género',
            diagnosis_label: 'Diagnóstico',
            current_status: 'Estado Actual',
            clinical_observations: 'Observaciones Clínicas',
            edit_notes: 'Editar notas',
            write_obs_placeholder: 'Escribe las observaciones aquí...',
            biomarker_evolution: 'Evolución de Biomarcadores',
            clinical_analysis: 'Análisis Clínico',
            voice_test_history: 'Historial de Pruebas de Voz',
            result: 'Resultado',
            view: 'Ver',
            stable: 'Estable',
            // Time/Period
            years_old: 'años',
            // Pagination
            previous: 'Anterior',
            next: 'Siguiente',
            of: 'de',
            // Médicos y Asignaciones
            doctors_management: 'Gestión de Médicos',
            doctor_patients_relation: 'Asignación de Pacientes',
            new_doctor: '+ Nuevo Médico',
            specialty: 'Especialidad',
            all_specialties: 'Todas las especialidades',
            view_patients: 'Ver pacientes',
            assigned_patients: 'Pacientes Asignados',
            doctor_directory_desc: 'Directorio central de profesionales de la salud',
            doctor_assignments_desc: 'Relación de pacientes por profesional médico',
            full_name_col: 'Nombre completo',
            license_col: 'Nº Licencia',
            status_col: 'Estado',
            active_status: 'Activo',
            inactive_status: 'Inactivo',
            search_doctor_placeholder: 'Buscar por nombre...',
            back_to_doctors: 'Volver a la lista de médicos',
            total_patients_assigned: 'pacientes en total',
            // Notas Clínicas
            clinical_notes: 'Notas Clínicas',
            add_note: 'Añadir Nota',
            note_type: 'Tipo',
            seguimiento: 'Seguimiento',
            observacion: 'Observación',
            inicial: 'Diagnóstico Inicial',
            save_note: 'Guardar Nota',
            no_diagnosis_yet: 'No se ha registrado un diagnóstico inicial aún.',
            invalid_email_format: 'Ingresa un correo electrónico válido.',
            password_too_short: 'La contraseña debe tener al menos 6 caracteres.',
            html_not_allowed: 'No se permiten etiquetas HTML por seguridad.',
            invalid_phone_format: 'Ingresa un número de teléfono válido (10 dígitos).',
            no_numbers_allowed: 'No se permiten números en este campo.',
            only_numbers_allowed: 'Solo se permiten números en este campo.'
        }
    };

    constructor() {
        // Sync with localStorage whenever signals change
        effect(() => {
            localStorage.setItem('darkMode', this.darkMode().toString());
            if (this.darkMode()) {
                document.body.classList.add('dark-mode');
            } else {
                document.body.classList.remove('dark-mode');
            }
        });

        effect(() => {
            localStorage.setItem('language', this.language());
        });
    }

    toggleDarkMode() {
        this.darkMode.set(!this.darkMode());
    }

    setLanguage(lang: Language) {
        this.language.set(lang);
    }

    translate(key: string): string {
        return this.translations[this.language()][key] || key;
    }
}
