services:
  # 1. Flask IA Microservice
  - type: web
    name: spark-ia
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    rootDir: ml
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9

  # 2. Express Backend
  - type: web
    name: spark-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    rootDir: backend/S_park_api
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: spark-db
          property: connectionString
      - key: ML_API_URL
        fromService:
          type: web
          name: spark-ia
          property: host
      - key: FLASK_API_URL
        fromService:
          type: web
          name: spark-ia
          property: host
      - key: JWT_SECRET
        generateValue: true

statics:
  # 3. Angular Static Frontend (Panel Administrativo)
  - name: spark-frontend
    buildCommand: npm install && npm run build
    publishDir: dist/S-park/browser
    rootDir: frontend
    plan: free

databases:
  # 4. PostgreSQL Database
  - name: spark-db
    plan: free